<a href="https://colab.research.google.com/github/HIsu1231/AI_INOVATION_SQUARE/blob/master/new_softmax.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [2]:
def softmax(z): #지수함수 특성상 값이 급격하게 증가하면 오버플로우 발생 가능
                #오버플로우 발생 방지를 위해 입력값 중 최대값을
                #모든 값에 동일하게 뺀 값으로 계산함

  c = np.max(z)

  numerator = np.exp(z-c)
  denominator = np.sum(np.exp(z-c))

  y = numerator / denominator 

  return y

In [3]:
A = np.array([0.7, 0.8, 0.01])

B = np.array([0.3, 2.9, 4.0])

C = np.array([110, 100, 90])

D = np.array([1000, 1100, 900])

In [4]:
print(softmax(A))
print(softmax(B))
print(softmax(C))
print(softmax(D))

[0.38361989 0.42396555 0.19241456]
[0.01821127 0.24519181 0.73659691]
[9.99954600e-01 4.53978686e-05 2.06106005e-09]
[3.72007598e-44 1.00000000e+00 1.38389653e-87]


In [6]:
print(np.sum(softmax(A)))
print(np.sum(softmax(B)))
print(np.sum(softmax(C)))
print(np.sum(softmax(D)))

1.0
1.0
1.0
1.0
