<a href="https://colab.research.google.com/github/HIsu1231/AI_INOVATION_SQUARE/blob/master/softmax.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [7]:
def softmax(a):

  numerator = np.exp(a)
  print("numerator = ",numerator)
  denominator = np.sum(np.exp(a))
  print("denominator = ",denominator)

  y = numerator / denominator

  return y 

In [8]:
A = np.array([0.7, 0.8, 0.01])

B = np.array([0.3, 2.9, 4.0])

C = np.array([110, 100, 90])

D = np.array([1000, 1100, 900])

In [9]:
print(softmax(A))

numerator =  [2.01375271 2.22554093 1.01005017]
denominator =  5.249343803047113
[0.38361989 0.42396555 0.19241456]


In [10]:
print(softmax(B))

numerator =  [ 1.34985881 18.17414537 54.59815003]
denominator =  74.1221542101633
[0.01821127 0.24519181 0.73659691]


In [11]:
print(softmax(C))

numerator =  [5.92097203e+47 2.68811714e+43 1.22040329e+39]
denominator =  5.921240851582884e+47
[9.99954600e-01 4.53978686e-05 2.06106005e-09]


In [13]:
print(softmax(D)) #오버플로우발생
                  #지수 함수 특성 상 값이 급격하게 커지면 오버플로우 발생 가능

numerator =  [inf inf inf]
denominator =  inf
[nan nan nan]


/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:3: RuntimeWarning: overflow encountered in exp
  This is separate from the ipykernel package so we can avoid doing imports until
/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:5: RuntimeWarning: overflow encountered in exp
  """
/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:8: RuntimeWarning: invalid value encountered in true_divide
  
